/**
 * Demo catalog content for the admin "Seed Demo Data" action.
 *
 * Photos are real, licensed images from Unsplash (Unsplash License —
 * free for commercial and non-commercial use, no attribution required),
 * hotlinked from their CDN as Unsplash's own guidelines allow. Product
 * names, descriptions, and prices are invented for this project.
 */

const img = (id, w = 900, h = 1125) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format&q=80`;

export const SEED_CATEGORIES = [
  {
    name: 'Newborn Essentials',
    slug: 'newborn-essentials',
    display_order: 1,
    description: 'Soft first pieces for the earliest days.',
    image_url: img('1510154221590-ff63e90a136f'),
  },
  {
    name: 'Onesies & Rompers',
    slug: 'onesies-rompers',
    display_order: 2,
    description: 'Easy one-piece essentials for everyday wear.',
    image_url: img('1622290319146-7b63df48a635'),
  },
  {
    name: 'Tops & T-Shirts',
    slug: 'tops-tshirts',
    display_order: 3,
    description: 'Everyday tops in soft, breathable cotton.',
    image_url: img('1546015720-b8b30df5aa27'),
  },
  {
    name: 'Bottoms',
    slug: 'bottoms',
    display_order: 4,
    description: 'Comfortable pants and shorts built for movement.',
    image_url: img('1556905055-8f358a7a47b2'),
  },
  {
    name: 'Dresses',
    slug: 'dresses',
    display_order: 5,
    description: 'Sweet, simple dresses for little ones.',
    image_url: img('1543346242-2b8e41fb91ca'),
  },
  {
    name: 'Co-ord Sets',
    slug: 'coord-sets',
    display_order: 6,
    description: 'Matching sets that make dressing simple.',
    image_url: img('1622290291468-a28f7a7dc6a8'),
  },
  {
    name: 'Sleepwear',
    slug: 'sleepwear',
    display_order: 7,
    description: 'Cosy, breathable sleepwear for better nights.',
    image_url: img('1622290291165-d341f1938b8a'),
  },
  {
    name: 'Winter Wear',
    slug: 'winter-wear',
    display_order: 8,
    description: 'Warm layers for cooler days.',
    image_url: img('1684244160171-97f5dac39204'),
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    display_order: 9,
    description: 'The little extras — hats, bibs, and more.',
    image_url: img('1569974641446-22542de88536'),
  },
];

/**
 * Each entry maps to one product. `category` is the slug from
 * SEED_CATEGORIES above (resolved to an id at seed time, since
 * categories must be created first to get real ids).
 */
export const SEED_PRODUCTS = [
  {
    name: 'Cotton Bunny Romper',
    slug: 'cotton-bunny-romper',
    category: 'onesies-rompers',
    description:
      'A soft, organic-cotton romper with a playful bunny print. Snap closures make changing quick and easy.',
    price: 799,
    compare_at_price: 999,
    age_group: '0-3 Months',
    gender: 'unisex',
    material: '100% Organic Cotton',
    care_instructions: 'Machine wash cold, tumble dry low',
    image_url: img('1622290319146-7b63df48a635'),
    rating: 4.8,
    is_featured: true,
    variants: [
      { size: '0-3M', color: 'Cream', stock: 14 },
      { size: '3-6M', color: 'Cream', stock: 9 },
      { size: '0-3M', color: 'Sage Green', stock: 6 },
    ],
  },
  {
    name: 'Newborn Welcome Set',
    slug: 'newborn-welcome-set',
    category: 'newborn-essentials',
    description:
      'A 5-piece essentials set for your baby’s first days home — romper, cap, mittens, booties, and a swaddle.',
    price: 1499,
    compare_at_price: null,
    age_group: '0-3 Months',
    gender: 'unisex',
    material: 'Cotton Blend',
    care_instructions: 'Machine wash cold, lay flat to dry',
    image_url: img('1510154221590-ff63e90a136f'),
    rating: 4.9,
    is_featured: true,
    variants: [
      { size: 'Newborn', color: 'White', stock: 11 },
      { size: 'Newborn', color: 'Butter Yellow', stock: 8 },
    ],
  },
  {
    name: 'Cloud Print Sleepsuit',
    slug: 'cloud-print-sleepsuit',
    category: 'sleepwear',
    description:
      'A dreamy cloud-print sleepsuit with flat seams and a two-way zip for easy midnight changes.',
    price: 899,
    compare_at_price: null,
    age_group: '3-6 Months',
    gender: 'unisex',
    material: '100% Cotton',
    care_instructions: 'Machine wash cold, do not bleach',
    image_url: img('1622290291165-d341f1938b8a'),
    rating: 4.7,
    is_featured: false,
    variants: [
      { size: '3-6M', color: 'Sky Blue', stock: 10 },
      { size: '6-12M', color: 'Sky Blue', stock: 7 },
      { size: '3-6M', color: 'Lavender', stock: 5 },
    ],
  },
  {
    name: 'Striped Cotton Tee',
    slug: 'striped-cotton-tee',
    category: 'tops-tshirts',
    description:
      'A everyday striped tee in breathable cotton jersey, cut generously for easy movement.',
    price: 549,
    compare_at_price: null,
    age_group: '1-2 Years',
    gender: 'unisex',
    material: '100% Cotton',
    care_instructions: 'Machine wash cold',
    image_url: img('1546015720-b8b30df5aa27'),
    rating: 4.5,
    is_featured: false,
    variants: [
      { size: '1-2Y', color: 'Grey Melange', stock: 13 },
      { size: '2-3Y', color: 'Grey Melange', stock: 9 },
      { size: '1-2Y', color: 'Dusty Rose', stock: 6 },
    ],
  },
  {
    name: 'Everyday Jogger Pants',
    slug: 'everyday-jogger-pants',
    category: 'bottoms',
    description:
      'Soft French terry joggers with an adjustable elastic waist that grows with your little one.',
    price: 699,
    compare_at_price: 849,
    age_group: '1-2 Years',
    gender: 'unisex',
    material: 'Cotton French Terry',
    care_instructions: 'Machine wash cold, tumble dry low',
    image_url: img('1556905055-8f358a7a47b2'),
    rating: 4.6,
    is_featured: false,
    variants: [
      { size: '1-2Y', color: 'Sage Green', stock: 12 },
      { size: '2-3Y', color: 'Sage Green', stock: 8 },
    ],
  },
  {
    name: 'Sunday Pinafore Dress',
    slug: 'sunday-pinafore-dress',
    category: 'dresses',
    description:
      'A simple pinafore dress in soft cotton poplin, made for twirling and everyday adventures alike.',
    price: 999,
    compare_at_price: null,
    age_group: '2-3 Years',
    gender: 'girl',
    material: 'Cotton Poplin',
    care_instructions: 'Machine wash cold, hang to dry',
    image_url: img('1543346242-2b8e41fb91ca'),
    rating: 4.8,
    is_featured: true,
    variants: [
      { size: '2-3Y', color: 'Dusty Rose', stock: 9 },
      { size: '1-2Y', color: 'Dusty Rose', stock: 6 },
      { size: '2-3Y', color: 'Butter Yellow', stock: 4 },
    ],
  },
  {
    name: 'Weekend Co-ord Set',
    slug: 'weekend-coord-set',
    category: 'coord-sets',
    description:
      'A relaxed tee-and-shorts set in matching soft cotton — the easiest way to get dressed on a busy morning.',
    price: 899,
    compare_at_price: null,
    age_group: '1-2 Years',
    gender: 'unisex',
    material: '100% Cotton',
    care_instructions: 'Machine wash cold',
    image_url: img('1622290291468-a28f7a7dc6a8'),
    rating: 4.6,
    is_featured: false,
    variants: [
      { size: '1-2Y', color: 'Sky Blue', stock: 10 },
      { size: '2-3Y', color: 'Sky Blue', stock: 7 },
    ],
  },
  {
    name: 'Quilted Puffer Jacket',
    slug: 'quilted-puffer-jacket',
    category: 'winter-wear',
    description:
      'A lightweight quilted jacket with a soft fleece lining, made to keep little ones warm without the bulk.',
    price: 1299,
    compare_at_price: 1599,
    age_group: '1-2 Years',
    gender: 'unisex',
    material: 'Polyester Shell, Fleece Lining',
    care_instructions: 'Machine wash cold, hang to dry',
    image_url: img('1684244160171-97f5dac39204'),
    rating: 4.7,
    is_featured: true,
    variants: [
      { size: '1-2Y', color: 'Grey Melange', stock: 8 },
      { size: '2-3Y', color: 'Grey Melange', stock: 6 },
    ],
  },
  {
    name: 'Soft Knit Beanie',
    slug: 'soft-knit-beanie',
    category: 'accessories',
    description: 'A gently stretchy knit beanie that keeps its shape wash after wash.',
    price: 349,
    compare_at_price: null,
    age_group: '6-12 Months',
    gender: 'unisex',
    material: 'Cotton Knit',
    care_instructions: 'Hand wash cold',
    image_url: img('1569974641446-22542de88536'),
    rating: 4.4,
    is_featured: false,
    variants: [
      { size: 'One Size', color: 'Cream', stock: 15 },
      { size: 'One Size', color: 'Dusty Rose', stock: 10 },
    ],
  },
  {
    name: 'Organic Muslin Swaddle',
    slug: 'organic-muslin-swaddle',
    category: 'newborn-essentials',
    description:
      'An extra-large muslin swaddle that softens with every wash — doubles as a nursing cover or stroller shade.',
    price: 599,
    compare_at_price: null,
    age_group: '0-3 Months',
    gender: 'unisex',
    material: '100% Organic Muslin Cotton',
    care_instructions: 'Machine wash cold',
    image_url: img('1470116945706-e6bf5d5a53ca'),
    rating: 4.9,
    is_featured: false,
    variants: [
      { size: 'One Size', color: 'Sage Green', stock: 20 },
      { size: 'One Size', color: 'White', stock: 16 },
    ],
  },
  {
    name: 'Button-Up Cardigan',
    slug: 'button-up-cardigan',
    category: 'tops-tshirts',
    description: 'A soft knit cardigan with wooden buttons — a cosy layer for cooler evenings.',
    price: 799,
    compare_at_price: null,
    age_group: '6-12 Months',
    gender: 'unisex',
    material: 'Cotton Knit',
    care_instructions: 'Hand wash cold, dry flat',
    image_url: img('1560506840-ec148e82a604'),
    rating: 4.6,
    is_featured: false,
    variants: [
      { size: '6-12M', color: 'Butter Yellow', stock: 9 },
      { size: '1-2Y', color: 'Butter Yellow', stock: 7 },
    ],
  },
  {
    name: 'Ribbed Footed Sleepsuit',
    slug: 'ribbed-footed-sleepsuit',
    category: 'sleepwear',
    description:
      'A snug, ribbed sleepsuit with covered feet — no more searching for lost socks at bedtime.',
    price: 649,
    compare_at_price: null,
    age_group: '3-6 Months',
    gender: 'unisex',
    material: '95% Cotton, 5% Elastane',
    care_instructions: 'Machine wash cold',
    image_url: img('1591161555818-7b9debeccc07'),
    rating: 4.7,
    is_featured: false,
    variants: [
      { size: '3-6M', color: 'Lavender', stock: 11 },
      { size: '6-12M', color: 'Lavender', stock: 8 },
    ],
  },
  {
    name: 'Denim-Look Dungarees',
    slug: 'denim-look-dungarees',
    category: 'bottoms',
    description:
      'Soft jersey dungarees with a denim-look print — easy poppers for quick changes, no rough denim.',
    price: 899,
    compare_at_price: null,
    age_group: '1-2 Years',
    gender: 'unisex',
    material: 'Cotton Jersey',
    care_instructions: 'Machine wash cold',
    image_url: img('1552819289-824d37ca69d2'),
    rating: 4.5,
    is_featured: false,
    variants: [
      { size: '1-2Y', color: 'Sky Blue', stock: 10 },
      { size: '2-3Y', color: 'Sky Blue', stock: 6 },
    ],
  },
  {
    name: 'Floral Puff-Sleeve Dress',
    slug: 'floral-puff-sleeve-dress',
    category: 'dresses',
    description:
      'A lightweight floral dress with gentle puff sleeves and a twirl-friendly hem.',
    price: 1099,
    compare_at_price: 1299,
    age_group: '2-3 Years',
    gender: 'girl',
    material: 'Cotton Voile',
    care_instructions: 'Machine wash cold, hang to dry',
    image_url: img('1596252732610-fce5ac542f8e'),
    rating: 4.8,
    is_featured: false,
    variants: [
      { size: '2-3Y', color: 'Dusty Rose', stock: 7 },
      { size: '1-2Y', color: 'Dusty Rose', stock: 5 },
    ],
  },
  {
    name: 'Terry Cloth Romper',
    slug: 'terry-cloth-romper',
    category: 'onesies-rompers',
    description: 'A textured terry romper that feels like a warm towel hug all day long.',
    price: 749,
    compare_at_price: null,
    age_group: '6-12 Months',
    gender: 'unisex',
    material: 'Cotton Terry',
    care_instructions: 'Machine wash cold, tumble dry low',
    image_url: img('1543342384-1f1350e27861'),
    rating: 4.6,
    is_featured: false,
    variants: [
      { size: '6-12M', color: 'Cream', stock: 12 },
      { size: '3-6M', color: 'Cream', stock: 9 },
    ],
  },
  {
    name: 'Knit Booties & Mitten Set',
    slug: 'knit-booties-mitten-set',
    category: 'accessories',
    description: 'A matching knit booties and mittens set to keep tiny hands and feet warm.',
    price: 449,
    compare_at_price: null,
    age_group: '0-3 Months',
    gender: 'unisex',
    material: 'Acrylic Knit',
    care_instructions: 'Hand wash cold',
    image_url: img('1608039649006-df579ad70c64'),
    rating: 4.5,
    is_featured: false,
    variants: [
      { size: 'One Size', color: 'Grey Melange', stock: 14 },
      { size: 'One Size', color: 'Sage Green', stock: 10 },
    ],
  },
  {
    name: 'Fleece-Lined Snowsuit',
    slug: 'fleece-lined-snowsuit',
    category: 'winter-wear',
    description:
      'A cosy all-in-one snowsuit with fleece lining and a fold-over cuff to protect little hands.',
    price: 1699,
    compare_at_price: 1999,
    age_group: '6-12 Months',
    gender: 'unisex',
    material: 'Polyester Shell, Fleece Lining',
    care_instructions: 'Machine wash cold, hang to dry',
    image_url: img('1580301762395-21ce84d00bc6'),
    rating: 4.9,
    is_featured: false,
    variants: [
      { size: '6-12M', color: 'Grey Melange', stock: 6 },
      { size: '1-2Y', color: 'Grey Melange', stock: 5 },
    ],
  },
  {
    name: 'Two-Piece Lounge Set',
    slug: 'two-piece-lounge-set',
    category: 'coord-sets',
    description: 'A relaxed-fit tee and pants set in soft ribbed cotton, perfect for lazy mornings.',
    price: 999,
    compare_at_price: null,
    age_group: '2-3 Years',
    gender: 'unisex',
    material: 'Ribbed Cotton',
    care_instructions: 'Machine wash cold',
    image_url: img('1566004100631-35d015d6a491'),
    rating: 4.6,
    is_featured: false,
    variants: [
      { size: '2-3Y', color: 'Butter Yellow', stock: 8 },
      { size: '1-2Y', color: 'Butter Yellow', stock: 6 },
    ],
  },
];
